id = "zed-volt"
name = "Volt Language Support"
version = "0.1.0"
schema_version = 1
authors = ["Yutsuna"]
description = "Volt language general support tools"
repository = "https://github.com/Yutsuna/zed-volt"

[grammars.volt]
repository = "https://github.com/Yutsuna/tree-sitter-volt"
rev = "a66c7b5d28e7dc77ea9736aac7c21e4eeb9ad2d2"
