id = "zed-volt"
name = "Volt Language Support"
version = "0.1.0"
schema_version = 1
authors = ["Yutsuna"]
description = "Volt language general support tools"
repository = "https://github.com/Yutsuna/zed-volt"

[grammars.volt]
repository = "https://github.com/Yutsuna/tree-sitter-volt"
rev = "ba43f7984316f080854eb27eb77a41787ca6deac"



